version: "3.7"
services:

  solver:
    build: ./Solver
    restart: always
    volumes:
      - ../assets/Solver:/code/assets
      - ../assets/data/cache/Solver:/code/cache
    networks:
      tabmatching-net:
        aliases:
         - solver.svc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - DOCKERIZED=True
      - DISABLE_MODELBASED_CORRECTIONS=True
  
  dbpedia_proxy:
    build: ./DBpedia_Proxy
    restart: always
    volumes:
      - ../assets/DBpedia_Proxy:/code/assets
      - ../assets/data/cache/DBpedia_Proxy:/code/cache
    networks:
      tabmatching-net:
        aliases:
          - proxy.dbpedia.svc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - 5003
    ports:
      - 5003:5003
    environment:
      - DOCKERIZED=True
      - MAX_PARALLEL_REQUESTS=5
      - DEFAULT_DELAY=10
      - MAX_RETRIES=5

  wikidata_proxy:
    build: ./Wikidata_Proxy
    restart: always
    volumes:
      - ../assets/Wikidata_Proxy:/code/assets
      - ../assets/data/cache/Wikidata_Proxy:/code/cache
    networks:
      tabmatching-net:
        aliases:
          - proxy.wikidata.svc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - 5007
    ports:
      - 5007:5007
    environment:
      - DOCKERIZED=True
      - MAX_PARALLEL_REQUESTS=5
      - DEFAULT_DELAY=10
      - MAX_RETRIES=5

  generic_lookup:
    build: ./Generic_Lookup
    restart: always
    volumes:
      - ../assets/data/cache/Generic_Lookup:/code/cache
    networks:
      tabmatching-net:
        aliases:
          - lookup.generic.svc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - 5010
    ports:
      - 5010:5010
    environment:
      - DOCKERIZED=True
    
  autocorrect:
    build: ./Autocorrect
    restart: always
    volumes:
      - ../assets/Autocorrect:/code/assets
      - ../assets/data/cache/Autocorrect:/code/cache
    networks:
      tabmatching-net:
        aliases:
         - autocorrect.svc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - 5005
    ports: 
      - 5005:5005
    environment:
      - DISABLE_MODELBASED_CORRECTIONS=True
      - DOCKERIZED=True

networks:
  tabmatching-net:
