OBJECT = "OBJECT"

DECIMAL = "DECIMAL"
PHONE = "PHONE"
BOOL = "BOOL"
URL__ = "URL"
EMAIl = "EMAIl"
NUMERAL = "NUMERAL"
VOLUME = "VOLUME"
AREA = "AREA"
DISTANCE = "DISTANCE"
TEMPRATURE = "TEMPRATURE"
DURATION = "DURATION"
ORDINAL = 'ORDINAL'
DATE = 'DATE'
LOCATION = 'LOCATION'

#spaCy types ...
CARDINAL = 'CARDINAL'
MONEY = 'MONEY'
PERCENT = 'PERCENT'
TIME = 'TIME'
QUANTITY = 'QUANTITY'

OTHER = 'OTHER' #Unknown

#internal types ... not supported for global use, DECIMAL is INT or FLOAT
FLOAT = "FLOAT"
INT = "INT"
