# default method is used when we don't have further option i.e., CTA is generated by only one method
default = 'default'  # CTA_Creation = default

# filtering methods
majority_vote = 'majorityVote'
unmatchedCpa = 'unmatchedCpa'
distantCea = 'distantCea'

# selection methods
stringSimilarity = 'stringSimilarity'
colSimilarity = 'colSimilarity'
missingCeaByCta = 'missingCeaByCta'

directParents = 'directParents'
lcs = 'LCS'
popularity = 'popularity'
